### PR TITLE
Rename (column -> mount_on)_will_change! in ActiveRecord

### PR DESCRIPTION
**Pull request by nviennot**
All the other methods do that

### CODE REVIEW

**Comment by bensie** [comment]
@nviennot Can you provide some additional reasoning for this?

**Comment by nviennot** [comment]
Consistency with the other `XXX_will_change!` calls:

https://github.com/nviennot/carrierwave/blob/master/lib/carrierwave/orm/activerecord.rb#L19-L20
https://github.com/nviennot/carrierwave/blob/master/lib/carrierwave/orm/activerecord.rb#L34-L35
https://github.com/nviennot/carrierwave/blob/master/lib/carrierwave/orm/activerecord.rb#L67-L69
https://github.com/nviennot/carrierwave/blob/master/lib/carrierwave/orm/activerecord.rb#L76-L77

that call in `remove_column` is the only one that doesn't lookup the serialization column. That's suspicious. Either `XXX_will_change!` takes a serialization column name, or a attribute name. But not both.

**Comment by thomasfedb** [comment]
This appears to be a sensible change, and code looks okay. Will however require tests. @nviennot are you able to add tests?

**Comment by nviennot** [comment]
I'm not sure what should be tested.

**Comment by bensie** [comment]
Ah I see now, makes sense. Thanks @nviennot!

**Comment by thomasfedb** [comment]
@bensie Do these changes request tests?

**Comment by bensie** [comment]
Not really, it just makes it consistent with the others like it.

**Pull request merged**
