### PR TITLE
Allow carrierwave to do safe or all redirections based on configuration

### PR DESCRIPTION
**Pull request by zdraganov**
I see plenty of historical issues to implement this and the best approach I see is [this PR](https://github.com/carrierwaveuploader/carrierwave/pull/2051) which seems to be opened in 2015. 

I've implemented my idea of option about download safety, so if you like it you can merge.

All the best from snowy Bulgaria folks! Keep doing such good work 😄

### CODE REVIEW

**Comment by janko-m** [comment]
Hmm, isn't the `open-uri` option for disabling/enabling redirects called `:redirect` instead of `:allow_redirections`?

**Comment by zdraganov** [comment]
Yeah, they are. But to be fully functional I wanted to implement http->https redirections with `:safe` option, and additionally https->http redirection with `:all` configuration option. That is achieved using external dependency called [open-uri-redirections](https://github.com/open-uri-redirections/open_uri_redirections) which is simply patching the redirection logic and adding thise functionality.
IMO same full functionality could be achieved with this idea https://github.com/carrierwaveuploader/carrierwave/pull/2051/files, but as I see it's not tested at all and there is a `puts` in the code.

**Comment by mshibuya** [comment]
This appears to be overkill, isn't it enough to require `open_uri_redirections` in your app and set `uploader.remote_image_request_header =  {allow_redirections: :all}` ?

**Comment by zdraganov** [comment]
I've didn't notice that option. I will test it and will give feedback.

**Comment by zdraganov** [comment]
@mshibuya where I can find `remote_image_request_header` option documented?

**Comment by zdraganov** [comment]
Just found that this option is missing in our current version (0.11.2), but existing in the latest carrierwave versions.
Closing it for now.

**Pull request closed without merging**
