### PR TITLE
Move to Rspec 3 syntax and update rspec version

### PR DESCRIPTION
**Pull request by eavgerinos**
### Changelog
 
- Update Rspec gem to version 3.2.0
- Update Cucumber gem to version 2.0.0
- Change all specs syntax to be compatible with the new rspec syntax.

### Rspec reference

- `obj.stub(:method)` is converted to `allow(obj).to receive(:method)`
- `expect(condition).to be_false` is converted to `expect(condition).to be_fausey`
- `expect(condition).to be_true` is converted to `expect(condition).to be_truthy`

---

The rationale behind this change is to have more clear specs and make it easier to maintain and extend our test suite which leads to easier adding/modifying of features.

### CODE REVIEW

**Comment by plribeiro3000** [comment]
Looking good so far! Great work. :+1:

**Comment by eavgerinos** [comment]
@bensie @plribeiro3000 Please review it after the build passes :)

**Comment by eavgerinos** [comment]
Fixed cucumber features also. I think it's ready.

**Comment by bensie** [comment]
Looks awesome!

**Pull request merged**
