### PR TITLE
Remove unwanted space from uploader template

### PR DESCRIPTION
**Pull request by amkurian**
Removed unwanted space from uploader template which was causing overcommit error.
carrierwave_overcommit

### CODE REVIEW

**Comment by anoobbava** [comment]
this issue is happening to me too.

**Comment by amkurian** [comment]
@mshibuya Please have a look

**Comment by mshibuya** [comment]
Thanks.

**Comment by amkurian** [comment]
@mshibuya Thank you for the prompt response.

**Pull request merged**
