### PR TITLE
Backport rspec3 matcher protocol deprecation fix

### PR DESCRIPTION
**Pull request by kreintjes**

### CODE REVIEW

**Comment by thiagofm** [comment]
Hello @kreintjes, unfortunately the build is failing for 1.9.3 for this patch.

**Comment by kreintjes** [comment]
Hi @thiagofm, the build is failing due to an error when installing the mime-types-data gem. I don't believe this has anything to do with my changes. In fact, the builds for the 0.11-stable branch and v0.11.0 tag are failing as well with the same errors.

**Comment by charliemaffitt** [comment]
:+1: Looking forward to deprecation errors being silenced

**Comment by kreintjes** [comment]
@thiagofm Could you or someone else have a look at this please? I don't believe my changes broke these builds, since they are already failing in 0.11-stable. I therefore think my PR does not make things worse, but instead improves something (since it fixes deprecation warnings). I do not have Ruby 1.9.3 installed, so I cannot test my changes or attempt to fix the problems in the 0.11-stable branch.

**Comment by thiagofm** [comment]
@kreintjes can you rerun the build? I believe it to be green now

**Comment by kreintjes** [comment]
@thiagofm all green now. Thanks!

**Pull request merged**
