### PR TITLE
Added Proc Support for Width and Height

### PR DESCRIPTION
**Pull request by tomprats**
I opened this issue (https://github.com/carrierwaveuploader/carrierwave/issues/2167) earlier this week and found a couple hacky solutions, so I thought I'd offer a more direct solution.

I then found this issue (https://github.com/carrierwaveuploader/carrierwave/issues/464) today and I think my fix would solve that problem as well, but may need to be updated to include something like [this](https://github.com/carrierwaveuploader/carrierwave/blob/540a84c606353a878d6574740e44f7970b754463/lib/carrierwave/uploader/configuration.rb#L150) in case some context needs to be passed in.

Let me know what you think! Thanks,
Tom

### CODE REVIEW

**Comment by tomprats** [comment]
Holy cow this actually works! Using my PR's code, I can now look up resizing values based on a field on the current model (or even the image being uploaded)

```
class SettingUploader < CarrierWave::Uploader::Base
  def self.width
    Proc.new do |uploader|
      # Default to enormous value to ensure height is used
      uploader.setting["width"] || 1000000000
    end
  end

  def self.height
    Proc.new do |uploader|
      # Default to enormous value to ensure width is used
      uploader.setting["height"] || 1000000000
    end
  end

  process resize_to_fit: [width, height]

  def setting
    # Get dimensions from DB or default to the image's current dimensions
    Setting.find_by(name: model.name) || { "width" => width, "height" => height }
  end
end
```

Hopefully someone decides to look at this at some point. For me, this feature adds a ton of capabilities for CarrierWave

**Comment by tomprats** [comment]
@mshibuya or whoever: Can I get your thoughts on this? Is there a better person to ping to get this moving?

**Comment by mshibuya** [comment]
Thanks for the PR, it will be nice to have a spec against a Proc with arity = 1(takes argument).

**Comment by tomprats** [comment]
@mshibuya I updated the tests and pulled in master to ensure other tests still pass

**Comment by mshibuya** [comment]
Thanks! 👍

**Pull request merged**
