### PR TITLE
Streaming of SanitizedFile.

### PR DESCRIPTION
**Pull request by TreyE**
Added streaming, where available, for moving/copying of SantizedFile.

This doesn't completely fix the issue with streaming, as that will require a re-work of the existing API to support chunked reads.  However, it does keep large files out of memory where possible (e.g. Streaming a large POST body as binary) - at least in the behaviour of sanitized file.

I'm aware there is a fairly bad hack to support the legacy api - but I can't see a way around it without major incompatibilities.

### CODE REVIEW

**Comment by bensie** [comment]
@TreyE Thanks for this. How would you rework the existing API to properly support this?

**Comment by bensie** [comment]
@TreyE If you do come back to this, please merge in the master branch, you'll have a better time with Travis testing :)

**Comment by TreyE** [comment]
The way I would re-work the existing file is to allow the File api to accept the standard IO read API.  Right now many of them only accept read with 0 arguments.

**Comment by bensie** [comment]
@TreyE We would welcome a patch for that if you're up for it :)

**Comment by kleyy** [comment]
+1

**Comment by thomasfedb** [comment]
@TreyE I'm closing this for now, but feel free to open a new PR if you'd like to attempt your proposed solution of allowing the File API to accept the standard IO #read API.

**Pull request closed without merging**
