### PR TITLE
Remove `CarrierWave::MimeTypes` processor module

### PR DESCRIPTION
**Pull request by mehlah**
Since #1245 (*), CarrierWave::MimeTypes module is redundant as `mime-types` gem is a runtime dependency now, and `SanitizedFile` gets it's content_type using it.
The module was deprecated since 0.10 and warned developers when used it.

What do you think about removing MagicMimeTypes processor module too?
I can't see any valid reason to keep it around.
A related side note: CarrierWave rely on ruby-filemagic gem (`MagicMime`) to validates the content type of a file against a white/blacklist.
I think we should use mime-types (`Mime::Types`) for this as it's a runtime dependency, and it's consistent with what it's used by `SanitizedFile` to set a content type.
Otherwise, we could use `MagicMime` everywhere as a runtime dependency instead of `Mime::Types`, but this kills JRuby support.

(*) I discovered this when tried to fix specs marked as pending. I looked at commits history and PRs to understand what happened.
It started with #372 that added `CarrierWave::MimeTypes`  processor (Jun 2011), then #1216 and #1245 that made `mime-types` a runtime dependency and deprecated `CarrierWave::MimeTypes` module (2013), and finally #1584 `CarrierWave::MagicMimeTypes` (2015)

### CODE REVIEW

**Comment by thomasfedb** [comment]
I'm happy to remove this processor module. It's clearly deprecated, and offers very little.

**Comment by thomasfedb** [comment]
I'd welcome a PR that removed the need for `MagicMime` if you can implement the same functionality with `Mime::Types`.

**Comment by mehlah** [comment]
@thomasfedb thanks for your feedback. I'll work on removing MagicMime then :+1: 
I rebased this against master.

**Comment by mehlah** [comment]
@thomasfedb I removed the need of `MagicMime` :dancer: 
 Work based on this branch:
https://github.com/mehlah/carrierwave/compare/remove-mimetypes-module...mehlah:remove-magicmime
I'll PR that as soon as this got merged

**Comment by earksiinni** [comment]
Just wanted to thank @mehlah for going through the extra effort of researching and documenting the history of `CarrierWave::MimeTypes`. It was a _huge_ help in figuring out what was going wrong while upgrading CarrierWave. Kudos!

**Comment by mehlah** [comment]
Thanks @earksiinni for the kind words ;)

**Pull request merged**
