### PR TITLE
Remove locales from main repository

### PR DESCRIPTION
**Pull request by mehlah**
As a follow up to #1823
This PR removes locales from main repository, in favor of a separate one only concerned with locales:
https://github.com/craftsmen/carrierwave-i18n
In addition to the reasons I described in #1823, this repo have better specs for [locales loading](https://github.com/craftsmen/carrierwave-i18n/blob/master/spec/locale_loading_spec.rb) and and [validity of yml manifests](https://github.com/craftsmen/carrierwave-i18n/blob/master/spec/carrierwave-i18n_spec.rb) that should always be in sync with the "en" one.

Users of CarrierWave who might need additional locales could either add carrierwave-i18n gem or simply copy/paste the needed locales to their applications (we could add a Wiki page with an example).

Thoughts?

### CODE REVIEW

**Comment by thomasfedb** [comment]
What are you thoughts on this @bensie. Are you able to organise to bring the `carrierwave-i18n` repo into the @carrierwaveuploader org?

**Comment by bensie** [comment]
Yes I can take care of the repo/gem. I'm not sure I see the benefit to splitting this out, but don't feel strongly about it.

**Comment by bensie** [comment]
I've made the repo at https://github.com/carrierwaveuploader/carrierwave-i18n, both of you should be able to push to it.

**Comment by thomasfedb** [comment]
@mehlah I will arrange to clone your repo into https://github.com/carrierwaveuploader/carrierwave-i18n. You may like to delete your repo and then fork from the official repo.

**Comment by thomasfedb** [comment]
@mehlah I've lodged a few issue with the new `-i18n` repo. Once these are sorted out I'll be able to merge this PR.

**Comment by mshibuya** [comment]
@mehlah Merged 🌟

**Comment by mehlah** [comment]
Thanks @mshibuya.

I have not taking much time lately to keep up with CarrierWave updates.
Let me know pls if there is anything I can help with, especially for i18n as I worked on it before.

**Pull request merged**
