### PR TITLE
Add CarrierWave::MagicMimeTypes

### PR DESCRIPTION
**Pull request by bensie**
Replacing #1559 with master merged and a few changes.

### CODE REVIEW

**Comment by eavgerinos** [comment]
In order to fix the travis errors I think we need something like

```
addons:
  apt_packages:
  - libmagic-dev
```
in the `travis.yml`

**Comment by bensie** [comment]
Haha I changed the branch yesterday for the same reason, I couldn't push :)

**Comment by eavgerinos** [comment]
It's ok :) Though you could have asked me to perform the changes you wished :)

**Comment by bensie** [comment]
@eavgerinos Travis is being dumb. You have to request that they whitelist apt packages before they can be used.

**Comment by eavgerinos** [comment]
@bensie meh :S Then let's send them a request :) Will you do it please (since you own the project)?

**Comment by bensie** [comment]
Done: https://github.com/travis-ci/travis-ci/issues/3331

**Comment by eavgerinos** [comment]
Perfect!

**Comment by bensie** [comment]
@eavgerinos ruby-filemagic appears unsupported on JRuby :(

**Comment by eavgerinos** [comment]
Well this is true since it has native extension in C, we can exclude it if `RUBY_ENGINE` is `jruby. Do you want a patch for this or you are against supporting different features between different rubies?

**Comment by bensie** [comment]
I'll gladly take a patch, especially since this is an optional processor. Thanks!

**Comment by bensie** [comment]
@eavgerinos If you want, you pull this branch locally, push to your fork, and reopen the PR. Or you can open a separate PR that targets this branch. Up to you.

**Comment by eavgerinos** [comment]
@bensie ok :) I'll open a PR directly to this branch, so it can be reviewed as a whole before it reach the master branch

**Comment by naaano** [comment]
can someone help please update wiki pages about this? This old module is still recommended as how to set content type in 2 pages

**Comment by thomasfedb** [comment]
@naaano Please open a new issue so we can track this properly and decide the best way to fix this problematic situation.

**Pull request merged**
