### PR TITLE
add Indonesian locale

### PR DESCRIPTION
**Pull request by saveav**
Add locale for Bahasa Indonesia (Indonesian)

### CODE REVIEW

**Comment by saveav** [comment]
Hey all, how do I re-run the test?

**Comment by thomasfedb** [comment]
@saveav I've restarted the build for you.

**Comment by thomasfedb** [comment]
@saveav Note that while the build has technically failed, it appears to be due to an issue unrelated to your changes.

**Comment by thomasfedb** [comment]
Whilst I don't speak Bahasa Indonesia and can't verify these myself, Google Translate suggests that these are at least reasonable. Thanks @saveav!

**Comment by saveav** [comment]
thanks @thomasfedb

**Comment by thomasfedb** [comment]
:sparkles:

**Pull request merged**
