### PR TITLE
Add allowed_types to content_type_whitelist_error

### PR DESCRIPTION
**Pull request by mhluska**
We already do this in `extension_whitelist.rb` so this just matches the functionality.

### CODE REVIEW

**Comment by mshibuya** [comment]
Looks good, but we need a test case which covers this feature.

**Comment by mhluska** [comment]
@mshibuya @jedrekdomanski I added the test now.

**Comment by jedrekdomanski** [comment]
Looks good to me

**Comment by mshibuya** [comment]
Great, thanks!

**Pull request merged**
