### PR TITLE
process mini magic commands with combine_options

### PR DESCRIPTION
**Pull request by bernabas**

### CODE REVIEW

**Comment by bernabas** [comment]
hey @eavgerinos, can you take a look at this when you have time? i made some changes for mini magick processings to take advantage of `combine_options` :) thanks

**Comment by bernabas** [comment]
more comments .... so basically, previously we would have to do

    resize_to_limit(200, 200) do |img|
      img.quality 90
    end

which would generate two commands

    [0.01s] mogrify -resize 130x130> <blah blah file name>
    [0.01s] mogrify -quality 90  <blah blah file name>

but with this change, we would do 

    resize_to_limit(200, 200, combine_options: {quality: 90})

and it generates one command
    
    [0.01s] mogrify -resize 130x130> -quality 90  <blah blah file name>

**Comment by abookyun** [comment]
Hence `combine_options` is more efficient way to execute commands, I'll put :+1: on this.

**Comment by thomasfedb** [comment]
Can we get this merged @bensie?

**Comment by bensie** [comment]
Thanks @bernabas!

**Comment by bernabas** [comment]
@bensie no problem, thanks for the merge

**Comment by krismartin** [comment]
@bernabas How can I use the combine_options to append a "+" operator (e.g. +antialias)?

https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/tool.rb#L163

**Pull request merged**
