### PR TITLE
(WIP) Change inheritance behavior (closes #1495, 1505)

### PR DESCRIPTION
**Pull request by kuraga**

### CODE REVIEW

**Comment by plribeiro3000** [comment]
cc/ @eavgerinos

**Comment by plribeiro3000** [comment]
@kuraga Thanks for your efforts!

**Comment by kuraga** [comment]
Seems like Travis doesn't work...

And should we add some docs?

**Comment by kuraga** [comment]
Oh no, seems like it's deeply breaking change...

**Comment by plribeiro3000** [comment]
i believe that add/changes in the docs would be awesome!

We might have to keep in mind that once we merge this feature we need to release `1.0.0` fast since this is a breaking change.

**Comment by kuraga** [comment]
After research: only [this test](https://github.com/kuraga/carrierwave/blob/master/spec/uploader/versions_spec.rb#L205-L213) is red on `master`. So, all we need is to solve #1495 .

**Comment by plribeiro3000** [comment]
:+1:

**Comment by kuraga** [comment]
Will think about another solution...

**Comment by plribeiro3000** [comment]
Let me know if you need any help!

**Comment by kuraga** [comment]
I need :smile: #1495

**Comment by plribeiro3000** [comment]
I can't reopen it. You will have to redo the diff. =s

**Comment by kuraga** [comment]
I'm talking about finding a solution, not reopening...

**Comment by plribeiro3000** [comment]
Oh. got it.

I'm afraid i'm not that into the issue yet so i don't know exactly how to help you in this one. =s

**Comment by kuraga** [comment]
See #1672

**Pull request closed without merging**
