### PR TITLE
Silence rspec 3 complains

### PR DESCRIPTION
**Pull request by randoum**
With backward-compatibility

### CODE REVIEW

**Comment by fluxusfrequency** [comment]
+1

**Comment by tom-lord** [comment]
+1, the last release was over a year ago - when will there be an official release resolving these rspec3 warnings?

**Comment by randoum** [comment]
Any plan to publish a gem?

**Comment by jankeesvw** [comment]
Seeing the same issue..

**Comment by nicolaslazartekaqui** [comment]
+1

**Comment by bensie** [comment]
We have a few blockers preventing an upcoming gem release, please point your `Gemfile` at GitHub if you really need these warnings blocked in the meantime.

**Pull request merged**
