### PR TITLE
Added a section in the readme to check for presence of file

### PR DESCRIPTION
**Pull request by Samy-Amar**
The programming school I work uses carrierwave, and this is an issue we get regularly with students, who want to check if a photo was uploaded or not to the model through an 'if' statement. 

The answer is surprisingly hard to find online, it's a hard one to guess at first glance, and I believe adding it to the readme would help a lot of people.

### CODE REVIEW

**Comment by thiagofm** [comment]
I like the idea, but the current Readme is already too big. Can you optimize it for brevity and "searchability"?

**Comment by Samy-Amar** [comment]
@thiagofm: I've made a second draft that fits in two lines, and should be searchable enough. Tell me what you think

**Comment by thiagofm** [comment]
👍  LGTM

**Comment by aried3r** [comment]
Is this different from doing `u.avatar?`?

**Pull request merged**
