### PR TITLE
Add mime type detection for MS Office files

### PR DESCRIPTION
**Pull request by anthonypenner**

### CODE REVIEW

**Comment by mshibuya** [comment]
Could you write a spec for this?

**Comment by anthonypenner** [comment]
If you comment out `require 'mimemagic/overlay'`, you will see the 2 new specs I added fail. I wasn't sure if I could somehow remove/add the require within the spec somehow to prove it's needed. Anyways I didn't want to get too complicated here. Let me know if you would like to see more tests.

**Comment by adamgaynor** [comment]
I am experiencing this issue when trying to use Carrierwave, would be great if this can be merged.

**Comment by alex-hedrevich** [comment]
@mshibuya 

when can this be merged?

**Comment by mshibuya** [comment]
Sorry for the long delay, thank you!

**Pull request merged**
