### PR TITLE
Run MRI 2.3 on Travis CI

### PR DESCRIPTION
**Pull request by mehlah**
:raising_hand:

### CODE REVIEW

**Comment by thomasfedb** [comment]
Is it necessary to specify `2.3.0` rather than `2.3`?

**Comment by mehlah** [comment]
I think currently we cannot specify the version as "2.3" since it does not work:
https://twitter.com/travisci/status/681909200591654913 and https://github.com/travis-ci/travis-ci/issues/5361#issuecomment-167536760
Maybe they fixed it since.

**Comment by thomasfedb** [comment]
If you can change the value in the Travis config that would be great. I'll arrange for this to be merged once https://github.com/travis-ci/travis-ci/issues/5361 is resolved.

**Comment by mehlah** [comment]
Done!
The issue is confirmed by https://travis-ci.org/carrierwaveuploader/carrierwave/jobs/102121398

**Comment by thedrow** [comment]
This should be closed now that #1910 is merged :)

**Pull request closed without merging**
